phenotips/patient-network

- pom.xml
- ui/src/main/resources/PhenoTips/VariantDisplay.xml
- Resolves issue #68: fixed UCSC link, fixed display formatting (chr capitalization and spacing)
- Resolved issue #70: fixed UCSC link
> Variant UI fixes

- similarity-search/src/main/java/org/phenotips/similarity/internal/SolrSimilarPatientsFinder.java
Limit the seeding search return to 50 rows.
> Limit the seeding search result

- similarity-search/src/main/java/org/phenotips/similarity/internal/SolrSimilarPatientsFinder.java
> PN-24: Better seeding of similar patients by matching the full HPO hierarchies of the reference patient's symptoms to the index.

- ui/src/main/resources/PhenoTips/SimilarCases.xml
- ui/src/main/resources/PhenoTips/VariantDisplay.xml
> PN-109: Percentiles of segmented bar for gene matching breakdown are not visible

- ui/src/main/resources/PhenoTips/SimilarCases.xml
> PN-108: Two boxes of features breakdown are not aligned.

- similarity-data-impl/src/main/java/org/phenotips/data/similarity/internal/DefaultPatientGenotype.java
- similarity-data-impl/src/test/java/org/phenotips/data/similarity/internal/RestrictedPatientGenotypeSimilarityViewTest.java
> PN-96: Use candidate genes and variants in patient matching.

- similarity-data-api/src/main/java/org/phenotips/data/similarity/PatientGenotypeSimilarityView.java
- similarity-data-impl/src/main/java/org/phenotips/data/similarity/internal/AbstractPatientGenotypeSimilarityView.java
- similarity-data-impl/src/main/java/org/phenotips/data/similarity/internal/DefaultPatientGenotype.java
- similarity-data-impl/src/main/java/org/phenotips/data/similarity/internal/DefaultPatientGenotypeSimilarityView.java
- similarity-data-impl/src/main/java/org/phenotips/data/similarity/internal/DefaultPatientSimilarityView.java
- similarity-data-impl/src/main/java/org/phenotips/data/similarity/internal/DefaultPatientSimilarityViewFactory.java
- similarity-data-impl/src/test/java/org/phenotips/data/similarity/internal/RestrictedPatientGenotypeSimilarityViewTest.java
- similarity-data-impl/src/test/java/org/phenotips/data/similarity/internal/RestrictedPatientSimilarityViewTest.java
- similarity-search/src/main/java/org/phenotips/similarity/internal/SolrSimilarPatientsFinder.java
- ui/src/main/resources/PhenoTips/SimilarCases.xml
> PN-90: Genotypic seeding results need to be combined with phenotypic seeding.

- similarity-data-impl/src/main/java/org/phenotips/data/similarity/internal/AbstractPatientSimilarityView.java
- similarity-data-impl/src/main/java/org/phenotips/data/similarity/internal/DefaultDisorderSimilarityView.java
- similarity-data-impl/src/main/java/org/phenotips/data/similarity/internal/RestrictedDisorderSimilarityView.java
- similarity-data-impl/src/main/java/org/phenotips/data/similarity/internal/RestrictedPatientSimilarityView.java
- similarity-data-impl/src/test/java/org/phenotips/data/similarity/internal/RestrictedDisorderSimilarityViewTest.java
- similarity-data-impl/src/test/java/org/phenotips/data/similarity/internal/RestrictedPatientSimilarityViewFactoryTest.java
- similarity-data-impl/src/test/java/org/phenotips/data/similarity/internal/RestrictedPatientSimilarityViewTest.java
- RestrictedDisorderSimilarityView now extends DefaultDisorderSimilarityView
> PN-82: reveal disorder for matchable cases

- ui/src/main/resources/PhenoTips/SimilarCases.xml
@allasm and @marta- please take a quick look and verify this 1-line fix is reasonable
> Update Similar Cases UIExtension to use updated consents

- communication/src/main/java/org/phenotips/messaging/internal/DefaultActionManager.java
- communication/src/main/java/org/phenotips/messaging/script/AnonymousCommunicationScriptService.java
- similarity-data-api/src/main/java/org/phenotips/data/similarity/PatientSimilarityView.java
- similarity-data-impl/src/main/java/org/phenotips/data/similarity/internal/AbstractPatientSimilarityView.java
- similarity-data-impl/src/main/java/org/phenotips/data/similarity/internal/AbstractVariant.java
- similarity-data-impl/src/main/java/org/phenotips/data/similarity/internal/RestrictedPatientSimilarityView.java
- similarity-data-impl/src/test/java/org/phenotips/data/similarity/internal/RestrictedDisorderSimilarityViewTest.java
- similarity-data-impl/src/test/java/org/phenotips/data/similarity/internal/RestrictedPatientSimilarityViewTest.java
- ui/src/main/resources/PhenoTips/MatchContact.xml
- ui/src/main/resources/PhenoTips/SimilarCases.xml
> PT-2184: Simplify contact owner form

- similarity-search/src/main/java/org/phenotips/similarity/internal/SolrSimilarPatientsFinder.java
1. Added hard limit to number of cases returned
1. Used PriorityQ to take them without fully sorting the list
> PN-104: added hard limit to number of similar cases returned

- scripts/exomiser_cron.py
- ui/src/main/resources/PhenomeCentral/ExportVCF.xml
The VCF	file selected within the PhenoTips UI is now used for Exomiser, rather than assuming that only one VCF is uploaded.
> PN-145: Improper handling when multiple vcf files are uploaded

- scripts/exomiser_cron.py
- scripts/exomiser_cron.sh
- scripts/exomiser_settings.txt
- similarity-data-impl/src/main/java/org/phenotips/data/similarity/internal/ExomiserExomeManager.java
- Updates cron script and Exomiser settings template to be 7.2.2-compatible
> PC-132: Upgrade to Exomiser 7.2.2

- ui/src/main/resources/PhenoTips/SimilarCases.xml
This is a temporary fix until a "Show more results" solution is implemented.
> PN-142: Limit number of matches that appear in the UI

- similarity-data-impl/src/main/resources/ApplicationResources.properties
- ui/src/main/resources/PhenoTips/SimilarCases.xml
- Unified the formatting of refresh buttons between patient-network and remote-matching
- Added support for service disclaimer modal
> RM-51: Improved matching service buttons

- pom.xml
- similarity-data-api/src/main/java/org/phenotips/data/similarity/MatchedPatientClusterView.java
- similarity-data-impl/src/main/java/org/phenotips/data/similarity/internal/DefaultMatchedPatientClusterView.java
- similarity-data-impl/src/main/resources/ApplicationResources.properties
- similarity-data-impl/src/main/resources/META-INF/components.txt
- similarity-data-impl/src/test/java/org/phenotips/data/similarity/internal/DefaultMatchedPatientClusterViewTest.java
- similarity-data-rest/pom.xml
- similarity-data-rest/src/main/java/org/phenotips/data/similarity/rest/PatientMatchResource.java
- similarity-data-rest/src/main/java/org/phenotips/data/similarity/rest/internal/DefaultPatientMatchResource.java
- similarity-data-rest/src/main/resources/META-INF/components.txt
- similarity-data-rest/src/test/java/org/phenotips/data/similarity/rest/internal/DefaultPatientMatchResourceTest.java
- similarity-search/src/main/java/org/phenotips/similarity/internal/SolrSimilarPatientsFinder.java
- ui/src/main/resources/PhenoTips/SimilarCases.xml
> PN-192: Allow pagination of the similarity results

- matching-notification-migrations/src/main/java/org/phenotips/matchingnotification/internal/R71503PatientNetwork196DataMigration.java
- matching-notification-migrations/src/main/java/org/phenotips/matchingnotification/internal/R71506PatientNetwork196DataMigration.java
- matching-notification-migrations/src/main/resources/META-INF/components.txt
… and update local matches with modified patients.
> PN-196: Create migrator to delete matches with deleted local patients and update local matches with modified patients

- similarity-data-impl/src/main/resources/ApplicationResources.properties
- ui/src/main/resources/PhenoTips/SimilarCases.xml
> PC-186: Improve Similar Cases table UI and rename Disorders column

- matching-notification-api/src/main/java/org/phenotips/matchingnotification/match/PatientInMatch.java
- matching-notification-api/src/main/java/org/phenotips/matchingnotification/match/internal/DefaultPatientInMatch.java
- matching-notification-api/src/main/resources/ApplicationResources.properties
- matching-notification-resources/src/main/resources/resources/uicomponents/matchingNotification/matchesTable.css
- matching-notification-resources/src/main/resources/resources/uicomponents/matchingNotification/matchesTable.js
- matching-notification-ui/src/main/resources/MatchingNotification/NotifiedTable.xml
- matching-notification-ui/src/main/resources/MatchingNotification/UnnotifiedTable.xml
- pom.xml
- similarity-data-api/src/main/java/org/phenotips/data/similarity/PatientGenotype.java
- similarity-data-api/src/main/java/org/phenotips/data/similarity/PatientGenotypeSimilarityView.java
- similarity-data-impl/pom.xml
- similarity-data-impl/src/main/java/org/phenotips/data/similarity/internal/AbstractPatientGenotypeSimilarityView.java
- similarity-data-impl/src/main/java/org/phenotips/data/similarity/internal/DefaultPatientGenotype.java
PN-206: Make patient ID and email searchable in 'matching notifications' table
PN-210: Expose externalid in the matching table and make it searchable
PN-199: Add new filters to 'matching notifications' table
> Matches table filtering

- matching-notification-resources/src/main/resources/resources/uicomponents/matchingNotification/matchesTable.js
- Fix cherry-picked artefact from future tranaslation work
> [bugfix] Translations will be introduces in 1.2

- pom.xml
- similarity-search/src/main/java/org/phenotips/similarity/SimilarPatientsFinder.java
- similarity-search/src/main/java/org/phenotips/similarity/internal/SolrSimilarPatientsFinder.java
- similarity-search/src/main/java/org/phenotips/similarity/script/SimilarPatientsScriptService.java
@sashaandjic please test (I will explain how on Slack)
> PN-256: Non-consented patients are considered as matches for incoming MME requests

- matching-notification-api/src/main/java/org/phenotips/matchingnotification/notification/internal/PatientMatchEmailNotifier.java
> PN-277: Multiple notifications are sent combined and multiple times

- matching-notification-ui/src/main/resources/MatchingNotification/MatchesTable.xml
> PN-292: My Matches page shows disabled remote servers as available filters

- matching-notification-api/src/main/java/org/phenotips/matchingnotification/match/internal/DefaultPatientInMatch.java
- matching-notification-resources/src/main/resources/resources/uicomponents/matchingNotification/matchesTable.js
- similarity-data-impl/src/main/java/org/phenotips/data/similarity/internal/AbstractPatientSimilarityView.java
- similarity-data-impl/src/main/java/org/phenotips/data/similarity/internal/RestrictedPatientSimilarityView.java
- ui/src/main/resources/PhenoTips/SimilarCases.xml
Adapted fetching solved case status and diplay multiple pubmed IDs for PT 1.4 changes
> [misc] More changes needed for upgrading to PT 1.4

- matching-notification-api/src/main/resources/ApplicationResources.properties
- matching-notification-resources/src/main/resources/resources/uicomponents/matchingNotification/matchesTable.js
- matching-notification-rest/src/main/java/org/phenotips/matchingnotification/rest/MatchingNotificationResource.java
- matching-notification-rest/src/main/java/org/phenotips/matchingnotification/rest/internal/DefaultMatchingNotificationResource.java
Added a 'Mark notified' button to the last column in the matches table if match is not notified yet
> PN-349: Add ability to mark matches that are manually contacted as notified in the matches table

- matching-notification-ui/src/main/resources/MatchingNotification/UserMatchNotificationEmailTemplate.xml
> PN-357: Fix issues with UserMatchNotificationEmailTemplate

- matching-notification-ui/src/main/resources/MatchingNotification/MatchesTable.xml
Fixed colspans for non-admin users.
> PN-301: Ability to mark matches as rejected/saved per user

- matching-notification-ui/src/main/resources/MatchingNotification/UserMatchNotificationEmailTemplate.xml
Changed back changes for stable aimed for PN 1.2
> PN-390: My patient link is broken in the contact email template

- matching-notification-api/src/main/resources/ApplicationResources.properties
- matching-notification-ui/src/main/resources/MatchingNotification/MatchesTable.xml
> PN-391: Modify text 'Overall' score to 'Average score'

- matching-notification-resources/src/main/resources/resources/uicomponents/matchingNotification/matchesTable.js
Added back deleted line that filters by genotypic score.
> PN-350: Add ability to filter out cases where owned match is solved

- matching-notification-resources/src/main/resources/resources/uicomponents/matchingNotification/matchesTable.js
> PN-394: Filtering by genotypic score is not working in the match notification table

- similarity-data-impl/src/main/java/org/phenotips/data/similarity/internal/DefaultPatientSimilarityView.java
A version of the https://github.com/phenotips/patient-network/pull/227 PR for the stable branch
> PN-393: (for stable branch) In the notification table, display adjusted phenotype score instead of plain phenotype score

- matching-notification-resources/src/main/resources/resources/uicomponents/matchingNotification/matchesTable.css
- matching-notification-resources/src/main/resources/resources/uicomponents/matchingNotification/matchesTable.js
- matching-notification-ui/src/main/resources/MatchingNotification/MatchesTable.xml
> PN-323 (stable): On My Matches page make match score search criteria more userfriendly

- matching-notification-resources/src/main/resources/resources/uicomponents/matchingNotification/matchesTable.css
- matching-notification-resources/src/main/resources/resources/uicomponents/matchingNotification/matchesTable.js
- matching-notification-ui/src/main/resources/MatchingNotification/MatchesTable.xml
> PN-323: On My Matches page make match score search criteria more user friendly

- matching-notification-api/src/main/resources/ApplicationResources.properties
- matching-notification-resources/src/main/resources/resources/uicomponents/matchingNotification/matchesTable.css
- matching-notification-ui/src/main/resources/MatchingNotification/MatchesTable.xml
> PN-396 (stable): Add labels to the score filters on the match notification table

- matching-notification-api/src/main/resources/ApplicationResources.properties
- matching-notification-resources/src/main/resources/resources/uicomponents/matchingNotification/matchesTable.css
- matching-notification-ui/src/main/resources/MatchingNotification/MatchesTable.xml
> PN-396: Add labels to the score filters on the match notification table

- matching-notification-api/src/main/java/org/phenotips/matchingnotification/storage/internal/DefaultMatchStorageManager.java
> PN-242: Rejected status may be lost for a match

- matching-notification-resources/src/main/resources/resources/uicomponents/matchingNotification/matchesTable.js
- matching-notification-ui/src/main/resources/MatchingNotification/MatchesTable.xml
> PN-417: Display all match locations in matching table with corresponding number of matches

- matching-notification-api/src/main/java/org/phenotips/matchingnotification/notification/internal/DefaultUserPatientMatchEmail.java
Fixed parsing user emails fetched from the user profile
> PN-420: When user has more than one email contact dialog is broken

- matching-notification-api/src/main/java/org/phenotips/matchingnotification/notification/internal/DefaultUserPatientMatchEmail.java
> PN-420-stable-1.x: When user has more than one email contact dialog is broken

- matching-notification-api/src/main/java/org/phenotips/matchingnotification/MatchingNotificationManager.java
- matching-notification-api/src/main/java/org/phenotips/matchingnotification/internal/DefaultMatchingNotificationManager.java
- matching-notification-api/src/main/java/org/phenotips/matchingnotification/match/PatientMatch.java
- matching-notification-api/src/main/java/org/phenotips/matchingnotification/match/internal/DefaultPatientMatch.java
- matching-notification-api/src/main/java/org/phenotips/matchingnotification/storage/MatchStorageManager.java
- matching-notification-api/src/main/java/org/phenotips/matchingnotification/storage/internal/DefaultMatchStorageManager.java
- matching-notification-api/src/main/resources/ApplicationResources.properties
- matching-notification-resources/src/main/resources/resources/uicomponents/matchingNotification/matchesTable.css
- matching-notification-resources/src/main/resources/resources/uicomponents/matchingNotification/matchesTable.js
- matching-notification-rest/src/main/java/org/phenotips/matchingnotification/rest/MatchingNotificationResource.java
- matching-notification-rest/src/main/java/org/phenotips/matchingnotification/rest/internal/DefaultMatchingNotificationResource.java
- matching-notification-ui/src/main/resources/MatchingNotification/MatchesTable.xml
> PN-404: Add ability to record "My notes" to each matching pair

- matching-notification-api/src/main/java/org/phenotips/matchingnotification/storage/MatchStorageManager.java
- matching-notification-api/src/main/java/org/phenotips/matchingnotification/storage/internal/DefaultMatchStorageManager.java
- matching-notification-resources/src/main/resources/resources/uicomponents/matchingNotification/matchesTable.js
- matching-notification-rest/src/main/java/org/phenotips/matchingnotification/rest/MatchingNotificationResource.java
- matching-notification-rest/src/main/java/org/phenotips/matchingnotification/rest/internal/DefaultMatchingNotificationResource.java
Added fromDate and toDate filters
Removed unused onlyNotified from API parameters for retrieving matches
> PN-431: API for retrieving "My Matches"

- matching-notification-ui/src/main/resources/MatchingNotification/MatchesTable.xml
Removed leftover href attribute
> PN-425: Better usability of send notifications button

- matching-notification-resources/src/main/resources/resources/uicomponents/matchingNotification/matchesTable.js
> PN-442: Disable ADD button for the blank notes on the My Matches page

- matching-notification-resources/src/main/resources/resources/uicomponents/matchingNotification/matcherPaginator.js
- matching-notification-resources/src/main/resources/resources/uicomponents/matchingNotification/matchesTable.css
- matching-notification-resources/src/main/resources/resources/uicomponents/matchingNotification/matchesTable.js
- matching-notification-ui/src/main/resources/MatchingNotification/MatchesTable.xml
> PN-441: Show page numbers on both sides of the My Matches grid and shorten list of page numbers

- matching-notification-api/src/main/java/org/phenotips/matchingnotification/storage/MatchStorageManager.java
- matching-notification-api/src/main/java/org/phenotips/matchingnotification/storage/internal/DefaultMatchStorageManager.java
- matching-notification-rest/src/main/java/org/phenotips/matchingnotification/rest/MatchingNotificationResource.java
- matching-notification-rest/src/main/java/org/phenotips/matchingnotification/rest/internal/DefaultMatchingNotificationResource.java
> PN-445: The response of the matches API should include information regarding how and when the returned results were obtained

- matching-notification-ui/src/main/resources/MatchingNotification/MatchesTable.xml
> PN-465: By default check all VCF data uploaded options on My Matches page

- matching-notification-api/src/main/java/org/phenotips/matchingnotification/match/PatientInMatch.java
- matching-notification-api/src/main/java/org/phenotips/matchingnotification/match/internal/DefaultPatientInMatch.java
- matching-notification-api/src/main/java/org/phenotips/matchingnotification/match/internal/DefaultPatientMatch.java
- matching-notification-api/src/main/resources/ApplicationResources.properties
- matching-notification-resources/src/main/resources/resources/uicomponents/matchingNotification/matchesTable.css
- matching-notification-resources/src/main/resources/resources/uicomponents/matchingNotification/matchesTable.js
- matching-notification-ui/src/main/resources/MatchingNotification/AdminMatchNotificationEmailTemplate.xml
- matching-notification-ui/src/main/resources/MatchingNotification/UserMatchNotificationEmailTemplate.xml
- similarity-data-api/src/main/java/org/phenotips/data/similarity/PatientSimilarityView.java
- similarity-data-impl/src/main/java/org/phenotips/data/similarity/internal/DefaultPatientSimilarityView.java
> PN-457: My Matches page is not showing matching genes if one side has vcf file uploaded

- matching-notification-api/src/main/java/org/phenotips/matchingnotification/match/internal/DefaultPatientInMatch.java
> PN-472 (stable): My Matches page is empty

- matching-notification-api/src/main/java/org/phenotips/matchingnotification/match/internal/DefaultPatientInMatch.java
> PN-472: My Matches page is empty

- similarity-search/src/main/java/org/phenotips/similarity/SimilarPatientsFinder.java
- similarity-search/src/main/java/org/phenotips/similarity/internal/SolrSimilarPatientsFinder.java
- similarity-search/src/main/java/org/phenotips/similarity/script/SimilarPatientsScriptService.java
Before this PR can be merged it should be rebased on top of PC which is based on a PT with PT-4004 included. Also some debug log messages useful for testing this PR should be removed before merging. Also need a copy of this PR for `master`
> PN-474 (stable): When searching for similar patients all patients with matching genes should be included in the matched list

- similarity-data-impl/src/main/resources/ApplicationResources.properties
- ui/src/main/resources/PhenoTips/SimilarCases.xml
> PN-231: Move all patient matches to a separate tab on the patient page

- matching-notification-resources/src/main/resources/resources/uicomponents/matchingNotification/matchesTable.js
> PN-488: If "%" is used either in discussion or in notes, saving will fail

- matching-notification-migrations/pom.xml
- matching-notification-migrations/src/main/java/org/phenotips/matchingnotification/internal/R74693PatientNetwork377DataMigration.java
> PN-483 (stable): The migrator for match comments saves the comments in invalid json format

- matching-notification-migrations/pom.xml
- matching-notification-migrations/src/main/java/org/phenotips/matchingnotification/internal/R74693PatientNetwork377DataMigration.java
> PN-483: The migrator for match comments saves the comments in invalid json format

- matching-notification-resources/src/main/resources/resources/uicomponents/matchingNotification/matchesTable.js
> PN-487: Sometimes the discussion comment does not get posted because ID is undefined

- matching-notification-resources/src/main/resources/resources/uicomponents/matchingNotification/matchesTable.css
- matching-notification-resources/src/main/resources/resources/uicomponents/matchingNotification/matchesTable.js
> PN-485: Make discussion window more user friendly

- matching-notification-api/src/main/java/org/phenotips/matchingnotification/match/internal/DefaultPatientInMatch.java
> PN-475: Inconsistent rules when displaying externalIDs of the matched record on Patient form and on My Matches page

- matching-notification-rest/src/main/java/org/phenotips/matchingnotification/rest/MatchingNotificationResource.java
Fixed bug with using QueryParam instead of FormParam
> PN-447: Refactor the Rest API for refreshing and retrieving matches

- matching-notification-resources/src/main/resources/resources/uicomponents/matchingNotification/matchesTable.css
- matching-notification-resources/src/main/resources/resources/uicomponents/matchingNotification/matchesTable.js
- matching-notification-ui/src/main/resources/MatchingNotification/MatchesTable.xml
> PN-486: Add Across MME checkbox to matches table filters

- matching-notification-api/src/main/java/org/phenotips/matchingnotification/internal/DefaultMatchingNotificationManager.java
- matching-notification-api/src/main/java/org/phenotips/matchingnotification/notification/PatientMatchNotificationResponse.java
- matching-notification-api/src/main/java/org/phenotips/matchingnotification/notification/PatientMatchNotifier.java
- matching-notification-api/src/main/java/org/phenotips/matchingnotification/notification/internal/PatientMatchEmailNotificationResponse.java
- matching-notification-api/src/main/java/org/phenotips/matchingnotification/notification/internal/PatientMatchEmailNotifier.java
- matching-notification-api/src/main/java/org/phenotips/matchingnotification/storage/MatchStorageManager.java
- matching-notification-api/src/main/java/org/phenotips/matchingnotification/storage/internal/DefaultMatchStorageManager.java
- matching-notification-rest/src/main/java/org/phenotips/matchingnotification/rest/internal/DefaultMatchingNotificationResource.java
> PN-278: When sending notifications for both incoming and outgoing versions of a match, an error is reported when it should not be

- matching-notification-api/src/main/java/org/phenotips/matchingnotification/match/PatientInMatch.java
- matching-notification-api/src/main/java/org/phenotips/matchingnotification/match/internal/AbstractPatientMatch.java
- matching-notification-api/src/main/java/org/phenotips/matchingnotification/match/internal/DefaultPatientInMatch.java
- matching-notification-api/src/main/java/org/phenotips/matchingnotification/notification/internal/AbstractPatientMatchEmail.java
- matching-notification-resources/src/main/resources/resources/uicomponents/matchingNotification/matchesTable.css
- matching-notification-resources/src/main/resources/resources/uicomponents/matchingNotification/matchesTable.js
> PN-413: Add information to the Reference and Matched columns to show institution/group that submitted the case

- matching-notification-migrations/src/main/java/org/phenotips/matchingnotification/internal/R74696PatientNetwork456DataMigration.java
> PN-505: PN-456 migration fails in production environment

- matching-notification-migrations/src/main/java/org/phenotips/matchingnotification/internal/R74696PatientNetwork456DataMigration.java
Rolled back the change which stopped the server after an error in the migrator
> PN-505: PN-456 migration fails in production environemnt

- matching-notification-resources/src/main/resources/resources/uicomponents/matchingNotification/matchDetailsView.js
Reverts phenotips/patient-network#303
> Revert "[misc] Parse remote patient ID in the match details dialog"

- matching-notification-resources/src/main/resources/resources/uicomponents/matchingNotification/matchesTable.js
Local patients should always be shown on the left side.
> PN-501: Improve the consistency within the matching table UI

- matching-notification-api/pom.xml
- matching-notification-api/src/main/java/org/phenotips/matchingnotification/storage/internal/DefaultMatchStorageManager.java
- matching-notification-api/src/main/resources/ApplicationResources.properties
- matching-notification-migrations/src/main/java/org/phenotips/matchingnotification/internal/R74697PatientNetwork506DataMigration.java
- matching-notification-resources/src/main/resources/resources/uicomponents/matchingNotification/matchesTable.js
- matching-notification-ui/src/main/resources/MatchingNotification/MatchesTable.xml
Update to remove complete duplicates of some matches
(which violate the assumption about the DB structure and are there due to a bug in old code)
> PN-506: Only keep one match per pair of patients
